# Generated by Django 5.2.5 on 2025-08-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TradePortal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.AlterField(
            model_name='company',
            name='scripcode',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='symbol',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
